version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /home/ubuntu/server
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  Install:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu


#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: ubuntu
