version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root
  Install:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: ubuntu
