version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      # Add any test/lint steps here if needed
      # - npm test

  build:
    commands:
      - echo "Building application..."
      # Optional build (if using React/Angular/Vue etc.)
      # - npm run build

  post_build:
    commands:
      - echo "Zipping artifacts for deployment..."
      - mkdir -p artifact
      - cp -r * artifact/
      - zip -r app.zip artifact/

artifacts:
  files:
    - app.zip
